### ISSUE TITLE
Duvida sobre o repositorio !!!

### ISSUE THREAD

**Issue by JoseRFJuniorLLMs** [Jean1dev/SpringBoot_Ionic#1]
api-rest-curso	estudos spring boot	last month
api-rest-principal	estudos spring boot	last month
jmsTemplate	estudos spring boot	last month
nodejs_worker	estudos spring boot	last month

Nao entendi por que tem 4 projeto, eu nao lembro disso no curso !! obrigado e abraco !!

**Comment by Jean1dev** [comment]
tem codigo alem do curso :D

api-rest-principal é o codigo original do curso
api-rest-curso é a minha implementacao
os restantes sao provas de conceito que eu fiz para complementar o estudo
